baseurl = "https://prag.io"
languageCode = "en-us"
title = "prag.io"
theme = ["hugo-redirect", "hyde"]
googleAnalytics = "UA-167472412-1"
copyright = "Pranjal Agrawal"
disqusShortname = "gcc42"

[Author]
	name = "Pranjal Agrawal"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[markup]
  [markup.highlight]
    style = "monokailight"

[params]
	description = "The Possimpible."
	linkedin = "https://linkedin.com/in/prag"
	github = "https://github.com/gcc42"
	twitter = "https://twitter.com/gcc_42"
	mainImage = "/phoenix.png"

[markup.goldmark.renderer]
	unsafe = true