baseurl = "https://prag.io"
languageCode = "en-us"
title = "prag.io"
theme = "hyde"
copyright = "Pranjal Agrawal"

[Author]
	name = "Pranjal Agrawal"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "The Possimpible."
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
	gplus = "https://plus.google.com/+NateFinch"
	disqus = "npfio"
	mainImage = "/phoenix.png"

[markup.goldmark.renderer]
	unsafe = true